{
	"version": 1594474596,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/playerred_walk-sheet0.png",
		"images/playerred_walk-sheet1.png",
		"images/playerred_walk-sheet2.png",
		"images/tilegreen_-sheet0.png",
		"images/enemyflying_-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/limit-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite-sheet0.png",
		"images/enemyswimming_-sheet0.png",
		"images/enemyswimming_-sheet1.png",
		"images/enemyswimming_-sheet2.png",
		"images/enemyspikey_-sheet0.png",
		"images/tiledbackground2.png",
		"images/tiledbackground3.png",
		"images/sprite4-sheet0.png",
		"images/skor-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/level1copy-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"media/collect gem.m4a",
		"media/collect gem.ogg",
		"media/jingle lose.m4a",
		"media/jingle lose.ogg",
		"media/jingle win.m4a",
		"media/jingle win.ogg",
		"media/mattoglseby - 1.m4a",
		"media/mattoglseby - 1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}